name: Deploy cdk lux stacks


permissions:
 id-token: write # Required for GitHub to be able to create a token for you to authenticate with AWS
 contents: read  # Permits your action to read this repo.


on:
 push:
   branches:
     - main


jobs:
 deploy_stack:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout this repo
       uses: actions/checkout@v3

     - name: Set up Node.js
       uses: actions/setup-node@v3
       with:
         node-version: '20'
     
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v2
       with:
         role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
         aws-region: ${{ vars.AWS_TARGET_REGION }}
         role-session-name: "GitHubActions-DeployLayerStack"


     - name: Deploy all stacks (via CDK)
       uses: youyo/aws-cdk-github-actions@v2
       with:
         cdk_subcommand: 'deploy'
         cdk_stack: '--all'
         cdk_args: '--require-approval never' 
         actions_comment: false